// originally planned to use https://api.quotable.io but the api is not working properly
// quotes generated by chatGPT so might have errors

const quotes = [
    "The best way to get started is to quit talking and begin doing.\n- Walt Disney",
    "Don't let yesterday take up too much of today.\n- Will Rogers",
    "It's not whether you get knocked down, it's whether you get up.\n- Vince Lombardi",
    "If you are working on something exciting, it will keep you motivated.\n- Unknown",
    "Success is not in what you have, but who you are.\n- Bo Bennett",
    "The harder you work for something, the greater you'll feel when you achieve it.\n- Unknown",
    "Dream bigger. Do bigger.\n- Unknown",
    "Don't watch the clock; do what it does. Keep going.\n- Sam Levenson",
    "Great things never come from comfort zones.\n- Neil Strauss",
    "Push yourself, because no one else is going to do it for you.\n- Unknown"
]

function getRandomColor() {
    const letters = '0123456789ABCDEF';
    let color = '#';
    for (let i = 0; i < 6; i++) {
        color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
}

async function getRandomQuote(){
    const quoteBox = document.getElementById('quotes');
    
    // Change background color
    document.body.style.backgroundColor = getRandomColor();

    const randomIndex = Math.floor(Math.random() * quotes.length);
    const randomQuote = quotes[randomIndex];

    quoteBox.style.opacity = 0;
    setTimeout(() => {
        quoteBox.innerText = randomQuote;
        quoteBox.style.opacity = 1;
    }, 300);
}

document.getElementById('drawButton').addEventListener('click', getRandomQuote);